### ISSUE TITLE
missing custom normals

### ISSUE THREAD

**Issue by nanogram** [ScanMountGoat/xenoblade_blender#1]
Left is blender import, right is gltf import from xc3_gltf. Blender import looks like mesh is missing normals.
![image](https://github.com/ScanMountGoat/xenoblade_blender/assets/14881073/b434a359-9993-48eb-bef9-b9a646383fe4)

**Comment by ScanMountGoat** [comment]
It looks like I forgot to load the normal and tangent attributes. This will be fixed for the next release.
