### ISSUE TITLE
Xenoblade3 heroes model

### ISSUE THREAD

**Issue by YuntianZi** [ScanMountGoat/xenoblade_blender#36]
I edit the heroes model in blender , and i export the wimdo format file based on the original file.  But when i added this mod to my game ,it stucked.This situation didn't happen on our 6 main characters body mode. Perhaps there's something wrong with heroes head.
![c8987f2ef25644c369c1aedc2254499b](https://github.com/ScanMountGoat/xenoblade_blender/assets/44439561/387a39fc-a47b-4fb7-a896-7db8e7d60754)

**Comment by YuntianZi** [comment]
This situation didn't happen on our 6 main characters body model

**Comment by ScanMountGoat** [comment]
Do you still have this problem if you export the model without any edits? I'm not seeing this issue on Ryujinx.

**Comment by YuntianZi** [comment]
Yes. Even if i export the model without any edits,it still stuck .Without edits ,the game at least shows some parts of the model before stuck, if  i do any edit  to the model , when i choose the hero ,it stuck immediately without showing anything.

**Comment by ScanMountGoat** [comment]
Does this happen on an actual switch? This may just be a yuzu issue.

**Comment by YuntianZi** [comment]
Thanks,i'll try it later.

**Comment by YuntianZi** [comment]
I just downloaded the Ryujinx emulator and tried my mods. The hero mod also makes Ryujinx shut down. The main characters mod  shows the new model corretly . Maybe my hero mod broken when i exported it.

**Comment by ScanMountGoat** [comment]
Can you upload the exported wimdo and wismt file in a zip? There may be an issue with the files.

**Comment by YuntianZi** [comment]
Good news! I can export heros mod correctly since i put my UI in English.
