### ISSUE TITLE
Material import fails when UI language is not English

### ISSUE THREAD

**Issue by YuntianZi** [ScanMountGoat/xenoblade_blender#38]
I used to import XB3 model in gltf format which is exported by xc3_lib ,and export model in wimdo format to build mod.
This time i tried to import model in wimdo format, but i failed.I Logs says " "Principled BSDF" not fount".
I use blender 4.1 and xenoblade_blender v0.9.0.
![5DDD3F084899B118271D6383B426F52A](https://github.com/ScanMountGoat/xenoblade_blender/assets/44439561/7587959f-b34f-498d-a3a4-2a84c310c073)

**Comment by YuntianZi** [comment]
Solved, I changed my language from simplified Chinese to English, now i can import model correctly.
![Uploading f2a703e0839431c15d19a2b4b607ccb8.png…]()

**Comment by ScanMountGoat** [comment]
You should always use the xenoblade_blender addon to import under the File > Import menu. The glTF models aren't compatible with the addon and are less accurate for materials.

**Comment by ScanMountGoat** [comment]
> Solved, I changed my language from simplified Chinese to English, now i can import model correctly.

I'll try and fix this for the next release. I'm able to reproduce this issue with Spanish as well. I'm not sure I would be able to figure out how to change back to English if I put my UI in Chinese.

**Comment by YuntianZi** [comment]
Good news! I can export heros mod correctly since i put my UI in English.

**Comment by YuntianZi** [comment]
> > Solved, I changed my language from simplified Chinese to English, now i can import model correctly.
> 
> I'll try and fix this for the next release. I'm able to reproduce this issue with Spanish as well. I'm not sure I would be able to figure out how to change back to English if I put my UI in Chinese.

You can change your language back in Blender using 编辑 > 偏好设置 > 界面 > 翻译 > 语言
![Uploading 5C24186AEF13B8BC527011275B1C73AB.png…]()

**Comment by ScanMountGoat** [comment]
Can you test if this is working on the latest release? If you're using Windows, you'll need to disable the addon in preferences, restart Blender, uninstall the addon, and install the new zip file.
https://github.com/ScanMountGoat/xenoblade_blender/releases/tag/v0.9.1

**Comment by YuntianZi** [comment]
> Can you test if this is working on the latest release? If you're using Windows, you'll need to disable the addon in preferences, restart Blender, uninstall the addon, and install the new zip file. https://github.com/ScanMountGoat/xenoblade_blender/releases/tag/v0.9.1

This new version addon can import and export wimdo correctly. Goodjob!
