### ISSUE TITLE
xeno1/map/ma0301.wismhd exceeds Blender internal limit of 8 UV maps

### ISSUE THREAD

**Issue by nanogram** [ScanMountGoat/xenoblade_blender#40]
Gaur Plains doesn't generate the full map for ma0301 & gets cut off.

![image](https://github.com/ScanMountGoat/xenoblade_blender/assets/14881073/b5b5d9f6-c92c-4d16-be54-6b6b783d166c)

**Comment by ScanMountGoat** [comment]
There's an uncaught exception that's getting triggered partway through the import process. You should see the error in the info log. I'll need to think about how I want to handle this limit.
