### ISSUE TITLE
"skin_toon" shader exports without outline mesh

### ISSUE THREAD

**Issue by YuntianZi** [ScanMountGoat/xenoblade_blender#41]
I export the wimdo file without any edit ,but the skin outline is disappear. How can i fix it?

![Sena](https://github.com/user-attachments/assets/b174d387-ed07-4a4e-93b8-694986042129)

**Comment by ScanMountGoat** [comment]
This a known limitation of the current exporting code and isn't something you can fix manually. I plan on supporting outlines in a future release, but it isn't a priority at the moment. https://github.com/ScanMountGoat/xenoblade_blender/wiki/Export#limitations

**Comment by YuntianZi** [comment]
Ok,thanks. Looking forward to your new version. : )

**Comment by ScanMountGoat** [comment]
This will be supported in the next release once I finish some more testing.
