### ISSUE TITLE
“ch04002410.wimdo” in XB3 makes the game crash

### ISSUE THREAD

**Issue by YuntianZi** [ScanMountGoat/xenoblade_blender#42]
This is Mio's City costume . Sometimes the mod makes the game crash, so i tried to ues the mod which I didn't change anything. But it still makes the game crash. By the way the highlignt on Mio's face changes from white to black.

**Comment by YuntianZi** [comment]
The game sometimes crashes ,sometimes stucks in the loading interface.
![010074f013262000_2024-07-24_11-40-48-007](https://github.com/user-attachments/assets/8c83f4cf-9e0d-4c41-a4cd-71346de05f96)

**Comment by ScanMountGoat** [comment]
I'm able to reproduce this on my end with chapter 6 cutscenes. I'll try and look into fixing this.
