### ISSUE TITLE
Imported/Exported face outlines don't render in-game for xeno2/model/bl/bl000301.wimdo and bl130201.wimdo  

### ISSUE THREAD

**Issue by tomasadam3** [ScanMountGoat/xenoblade_blender#43]
I'm not sure if this issue is exclusive to Pneuma and Massive Melee Mythra's models, or if other outlines are also affected, but for some reason their face outlines appear to be the only outlines that don't render in-game following the wimdo export. I've attached a copy of the exported Mythra model below:

[model.zip](https://github.com/user-attachments/files/16401065/model.zip)

**Comment by ScanMountGoat** [comment]
I'm able to reproduce this in game.
