### ISSUE TITLE
outlines rendered in XB3 become thicker

### ISSUE THREAD

**Issue by YuntianZi** [ScanMountGoat/xenoblade_blender#44]
I simply add a sphere which is added "OutlineVertexColor" and "Solidify Outlines" modifier to test the new release. But the outline of the sphere is thicker than other parts of the body. The body which has the same material as the sphere is also has a thicker outline. I can't fix it by adjusting the parameters of the  Solidify modifier.
I've attached my blender project and the new model below:
[OutlineTest.zip](https://github.com/user-attachments/files/16401493/OutlineTest.zip)
![010074f013262000_2024-07-28_04-57-25-094](https://github.com/user-attachments/assets/e331f3f3-9cd4-4b5f-be96-cbb539b700de)

**Comment by ScanMountGoat** [comment]
The outline thickness still hasn't been fully researched. You'll need to experiment with the vertex color alpha using existing meshes as a reference. https://github.com/ScanMountGoat/xenoblade_blender/wiki/Export#outlines

**Comment by YuntianZi** [comment]
I change the vertex color alpha, then l got the correct outline. The outline thickness will be thicker if the value of the vertex color alpha is closer to 1.
![%7B62DD2E3C-56F8-48e4-8242-58DECEDB224B%7D](https://github.com/user-attachments/assets/707b275d-abcb-4741-ab79-ee388d17aca0)

**Comment by ScanMountGoat** [comment]
This will be controlled by the "OutlineThickness" vertex group in the next release.

**Comment by YuntianZi** [comment]
Can the outline thickness also be controlled by the alpha of the "OutlineVertex" vertex group in the next release? So that i will not have to  redo my work.
For example ,if the model dont' have the "OutlineThickness" vertex group, then use the alpha of the "OutlineVertex" vertex group to control the thickness. In this way, the v0.12.0 release can also support projects which are made for the v0.11.0 release.

**Comment by ScanMountGoat** [comment]
The existing OutlineVertexColor alpha will be used if the OutlineWidth vertex group isn't present. You shouldn't need to redo anything in the next release at least for outlines.
