### ISSUE TITLE
Models render as solid color at a distance

### ISSUE THREAD

**Issue by YuntianZi** [ScanMountGoat/xenoblade_blender#49]
![010074f013262000_2024-08-23_09-09-21-112](https://github.com/user-attachments/assets/859d25a1-6cb8-4a44-bafd-4023a68fe9d8)
![010074f013262000_2024-08-23_09-09-31-056](https://github.com/user-attachments/assets/c2a6f5e4-a61b-4398-9da9-da86fd039ff5)
![010074f013262000_2024-08-23_09-09-31-696](https://github.com/user-attachments/assets/5f43edcf-aca3-47cd-8dfe-c6b23e598987)

**Comment by ScanMountGoat** [comment]
It could be a level of detail (LOD) issue. What file path are you replacing?

**Comment by YuntianZi** [comment]
She's a DLC character and the file path is "romfs\chr\ch\ch33003110.wimdo".If this is a LOD issue ,may be every replaced model has this error. I'll test it later.

**Comment by YuntianZi** [comment]
I have tested the other Models, included other heros and kevis soldiers. They all have this error.

**Comment by ScanMountGoat** [comment]
That should make it easier for me to test. Thanks.

**Comment by ScanMountGoat** [comment]
Does the issue go away after you get close to the model? It looks like the high resolution textures haven't been loaded yet. If you get close to the model at least once, the textures should look normal after moving far away again.

**Comment by YuntianZi** [comment]
Yes. After i get close to the model once, it renders correctly.But if i'm far form it enough, the issue shows up again when i'm getting close to it.

**Comment by ScanMountGoat** [comment]
Is this fixed for you on the latest release?
https://github.com/ScanMountGoat/xenoblade_blender/releases/tag/v0.14.0

**Comment by YuntianZi** [comment]
Yes, it's fixed.I really appreciate your quickly reply and new release.
