### ISSUE TITLE
DLL Load failed

### ISSUE THREAD

**Issue by Aelen-Calysta** [ScanMountGoat/xenoblade_blender#53]
Hello,

My goal is to import .camdo files in blender but this append when i wanted to import your addon.
I need help '-_-

![1](https://github.com/user-attachments/assets/068a5d58-d469-4fbd-83aa-9c9cff0ec4bd)
![2](https://github.com/user-attachments/assets/c099348b-644e-4f69-b0b0-07ad19d1d823)

**Comment by Aelen-Calysta** [comment]
Do you have any idea of this???

**Comment by ScanMountGoat** [comment]
xenoblade_blender releases are only compatible with specific Blender versions. You need to install Blender 4.2 to be able to use the latest version of xenoblade_blender. None of the releases are compatible with Blender 3.6.

**Comment by Aelen-Calysta** [comment]
Woahh, that was really quick!!!! Thank you so much, for your answer, and for your work!!!
