### ISSUE TITLE
Armature not importing

### ISSUE THREAD

**Issue by Ben10dom1** [ScanMountGoat/xenoblade_blender#55]
When importing the wimdo file it does not import the Armature correctly is there any fix for this?

**Comment by ScanMountGoat** [comment]
What file name are you importing?

**Comment by Ben10dom1** [comment]
im currently importing pc000201.wimdo for Nia im just getting a armature with no bones

**Comment by ScanMountGoat** [comment]
Do you have the arc and wismt file in the same folder as the wimdo? That file is importing fine for me.

**Comment by Ben10dom1** [comment]
I have the wismt file in the same folder but i dont have the arc file

**Comment by ScanMountGoat** [comment]
The arc contains the skeleton information for Xenoblade 2 models. I'll try and make this error more obvious for the next release.

**Comment by Ben10dom1** [comment]
ah okay

**Comment by Ben10dom1** [comment]
new to ripping this stuff and i cant find any info about it
