### ISSUE TITLE
xeno2/model/bl/bl000301.wimdo Editing the toon gradient of a duplicated material also edits the original material post-export

### ISSUE THREAD

**Issue by tomasadam3** [ScanMountGoat/xenoblade_blender#60]
The skin meshes of my Swimsuit Pneuma models currently use duplicates of Pneuma's face material (hikari_face_TS7_shape) in order to get the right look/generate outlines. I was looking to edit the toon gradients of only those (duplicated) materials, but after exporting the original face material was edited as well (both toon gradient values changing from 2 to 12).

Unedited 
![1](https://github.com/user-attachments/assets/c54cb583-cda1-4467-8c2b-9e61f6bda22a)

Edited 
![2](https://github.com/user-attachments/assets/4971ae8d-19ce-4c78-b825-5bbb3d2cf10c)

**Comment by ScanMountGoat** [comment]
What are the full names of the two materials in Blender? There may be something weird going on internally with copying the materials that I need to fix.

**Comment by tomasadam3** [comment]
The original material is named 6._hikari_face_TS7_shape, and the duplicate material is named 6._hikari_face_TS7_shape_skin
