### ISSUE TITLE
Unable to load skeleton for model

### ISSUE THREAD

**Issue by YuntianZi** [ScanMountGoat/xenoblade_blender#62]
I import the wimdo file by using the latest issue(0.16.1) ,but it shows "Unable to load skeleton for model with skin weights. The .arc or .chr file is missing or does not contain bone data."
How can i get these files.

**Comment by YuntianZi** [comment]
Acually, i already hane these files.Bit it still can not load the skeleton.
![04BE56A6A4FAB5FDF3D2A918B63E4665](https://github.com/user-attachments/assets/6ed46cba-842d-46c1-8c7f-3a3702a591c2)

**Comment by YuntianZi** [comment]
It seems that the situation only shows on Noah's model. I can import other character's files correctly

**Comment by ScanMountGoat** [comment]
Not all of the wimdo files have the complete skeleton or any skeleton at all. It won't impact model exports at all. You can reparent the meshes to the full armature in Blender for animations.
